export const IMAGE_ASSETS = {
  frameOptions: {
    sm: '/images/frames/frame-sm.jpg',
    md: '/images/frames/frame-md.jpg',
    lg: '/images/frames/frame-lg.jpg',
  },
  legoParts: {
    hair: {
      hair1: '/images/lego/hair/hair1.png',
      hair2: '/images/lego/hair/hair2.png',
      hair3: '/images/lego/hair/hair3.png',
      hair4: '/images/lego/hair/hair4.png',
      hair5: '/images/lego/hair/hair5.png',
    },
    face: {
      face1: '/images/lego/face/face1.png',
      face2: '/images/lego/face/face2.png',
      face3: '/images/lego/face/face3.png',
      face4: '/images/lego/face/face4.png',
      face5: '/images/lego/face/face5.png',
    },
    shirt: {
      shirt1_white: '/images/lego/shirt/shirt1_white.png',
      shirt1_red: '/images/lego/shirt/shirt1_red.png',
      shirt1_blue: '/images/lego/shirt/shirt1_blue.png',
      shirt2: '/images/lego/shirt/shirt2.png',
      shirt3: '/images/lego/shirt/shirt3.png',
      shirt4: '/images/lego/shirt/shirt4.png',
      shirt5: '/images/lego/shirt/shirt5.png',
    },
    pants: {
      pants1_black: '/images/lego/pants/pants1_black.png',
      pants1_beige: '/images/lego/pants/pants1_beige.png',
      pants1_gray: '/images/lego/pants/pants1_gray.png',
      pants2: '/images/lego/pants/pants2.png',
      pants3: '/images/lego/pants/pants3.png',
      pants4: '/images/lego/pants/pants4.png',
      pants5: '/images/lego/pants/pants5.png',
    },
    hat: {
      hat1: '/images/lego/hat/hat1.png',
      hat2: '/images/lego/hat/hat2.png',
      hat3: '/images/lego/hat/hat3.png',
    },
    accessory: {
      accessory1: '/images/lego/accessory/accessory1.png',
      accessory2: '/images/lego/accessory/accessory2.png',
      accessory3: '/images/lego/accessory/accessory3.png',
      accessory4: '/images/lego/accessory/accessory4.png',
      accessory5: '/images/lego/accessory/accessory5.png',
    },
    pet: {
      pet1: '/images/lego/pet/pet1.png',
      pet2: '/images/lego/pet/pet2.png',
      pet3: '/images/lego/pet/pet3.png',
    },
  },
  presetBackgrounds: {
    square: {
      kyniem1: '/images/backgrounds/square/kyniem1.jpg',
      kyniem3: '/images/backgrounds/square/kyniem3.jpg',
      kyniem4: '/images/backgrounds/square/kyniem4.jpg',
      sinh_nhat1: '/images/backgrounds/square/sinh-nhat1.jpg',
      sinh_nhat4: '/images/backgrounds/square/sinh-nhat4.jpg',
      sinh_nhat5: '/images/backgrounds/square/sinh-nhat5.jpg',
      tot_nghiep2: '/images/backgrounds/square/tot-nghiep2.jpg',
      valentine: '/images/backgrounds/square/valentine.jpg',
      dam_cuoi: '/images/backgrounds/square/dam-cuoi.jpg',
      spotify: '/images/backgrounds/square/spotify.jpg',
      sinh_nhat_bg: '/images/backgrounds/square/sinh-nhat-bg.jpg',
    },
    rectangle: {
      football1: '/images/backgrounds/rectangle/football1.jpg',
      football2: '/images/backgrounds/rectangle/football2.jpg',
      football3: '/images/backgrounds/rectangle/football3.jpg',
      football4: '/images/backgrounds/rectangle/football4.jpg',
      tot_nghiep3: '/images/backgrounds/rectangle/tot-nghiep3.jpg',
      album1: '/images/backgrounds/rectangle/album1.jpg',
      album2: '/images/backgrounds/rectangle/album2.jpg',
    },
  },
  collectionTemplates: {
    wedding: '/images/collections/wedding.jpg',
    graduation: '/images/collections/graduation.jpg',
    birthday: '/images/collections/birthday.jpg',
  },
  feedback: {
    minhAnh: '/images/feedback/minh-anh.jpg',
    giaDinhBap: '/images/feedback/gia-dinh-bap.jpg',
    hoangLong: '/images/feedback/hoang-long.jpg',
    thuyChi: '/images/feedback/thuy-chi.jpg',
  },
  productHighlights: {
    wedding: '/images/highlights/wedding.jpg',
    graduation: '/images/highlights/graduation.jpg',
    family: '/images/highlights/family.jpg',
    birthday: '/images/highlights/birthday.jpg',
  },
  general: {
    hero: '/images/general/hero.jpg',
    inspire: '/images/general/inspire.jpg',
    giftbox: '/images/general/giftbox.jpg',
    vietqr: '/images/general/vietqr.jpg',
  },
};